name: Build and Push to Docker Hub
on:
  push:
    branches: [main]

jobs:
  build:
    name: "Build and Push to  Docker Hub"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test to build Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            NEXT_PUBLIC_API_URL=https://api.oaku.sa.ku.ac.th
            NEXT_PUBLIC_KUALL_REDIRECT_URI=https://oaku.sa.ku.ac.th/auth/kualllogin/callback
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/oaku-frontend:latest